version: '3.7'

services:
  web:
    build:
      context: .
      target: ${APP_ENV}
      dockerfile: ./docker/Dockerfile
      args:
        - APP_ENV=${APP_ENV}
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - '80:80'
    restart: always